### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by Ramilito** [Ramilito/kubesess#20]
**Describe the bug**

Windows uses a different default kubeconfig path while we are using only the linux/mac ones.

**Expected behavior**

Should work on windows

**Screenshots**

<img width="488" alt="image" src="https://user-images.githubusercontent.com/8473233/187650362-3a2793e4-264c-4a51-8b0f-d744cd5c1b5a.png">

**Comment by Ramilito** [comment]
If anyone needs this please comment here, will prioritize other things if no interest since I don't think there are many that use kubectl on Windows (works on wsl).

**Comment by natescherer** [comment]
Hello! I've started taking a look at what it would take to add Windows support to kubesess and have run into a fairly sizeable problem: [skim doesn't work on Windows](https://github.com/skim-rs/skim?tab=readme-ov-file#shell-completions).

Would you be willing to entertain switching from skim to something like [heatseeker](https://github.com/rschmitt/heatseeker) that works on Windows?

Fully understand if you don't want to make a change like that, and would be happy to work on my own forked project if not.

**Comment by Ramilito** [comment]
Hey!

I appreciate you looking into this 🙌!

I don't have any attachment to skim-rs, however, I'm not liking the appearance and it seems that it requires setup by the user to work? or am I wrong here?

Do we have any other crates we could use?

**Comment by natescherer** [comment]
Heatseeker was just something I found while looking for skim replacements that work on Windows, after digging a bit deeper it looks like a better choice might be https://github.com/helix-editor/nucleo, which seems to be a lot closer to skim/fzf.

Thoughts?

**Comment by Ramilito** [comment]
I think nucleo looks awesome 👍

**Comment by natescherer** [comment]
Cool! I'll take a stab at refactoring to use nucleo instead of skim and see where that gets us for Windows compatability.

**Comment by Ramilito** [comment]
Let me know what other road bumps you stumble on, I might be able to help!
