### ISSUE TITLE
Add option to retrieve current context and namespace

### ISSUE THREAD

**Issue by MisterTimn** [Ramilito/kubesess#24]
**Describe the solution you'd like**
A flag to output the current context and namespaces OR environment variables that get populated on context change.
This can then be used to build a custom prompt.

**Describe alternatives you've considered**
Right now I use `kubectx -c` and `kubens -c` to get context and namespace to build my prompt. I use this in favor of other solutions because it is significantly faster.

**Additional context**
Since `kubesess` is apparently more efficient than those tools to switch context/namespace, I was wondering if retrieval of current values would perhaps be as fast or even faster.

If this is added, then I wouldn't have a need for `kubectx` any longer

**Comment by Ramilito** [comment]
That sounds like a good idea!
I've been using p10k but have been thinking of doing it myself.

The command would look like this: ```kubesess -c context``` and ```kubesess -c namespace```

I'll add the same functionality to the default commands as well, might be useful, that would look like: ```kubesess -c default-context``` and ```kubesess -c default-namespace```


Did some preliminary testing, and it looks promising!

Getting current context
<img width="496" alt="image" src="https://user-images.githubusercontent.com/8473233/188755383-9b4fad3f-40c5-47af-9ef1-5dbb563f2424.png">

Getting current namespace
<img width="501" alt="image" src="https://user-images.githubusercontent.com/8473233/188756429-bca46324-9821-4da6-9366-69945066137a.png">

**Comment by Ramilito** [comment]
There is a release now, both in binary and homebrew with this feature!

**Comment by Ramilito** [comment]
Would love it if you would share your prompt script?

**Comment by MisterTimn** [comment]
```
prompt_context() {
    KUBE_CTX=$(kubesess -c context)
    KUBE_NS=$(kubesess -c namespace)
    KUBE_PS1="$KUBE_CTX/$KUBE_NS"
    if [[ $KUBE_CTX == *"staging"* ]]; then
        prompt_segment yellow black "$KUBE_PS1"
    elif [[ $KUBE_CTX == *"prod"* ]]; then
        prompt_segment red black "$KUBE_PS1"
    else
        prompt_segment green black "$KUBE_PS1"
    fi
}
```

This is using the agnoster theme with zsh/oh-my-zsh. Mainly wanted it to be very clear wether im deploying to production, staging or dev clusters.
![image](https://user-images.githubusercontent.com/4209558/188819209-9aa66360-26d4-4bb9-9f4c-e537b420d62d.png)


Also I've been hacking together a way to merge all my configs, so far coming up with this (all my base configs have .yaml extension)
```
KUBECONFIG=$(for YAML in $(find ${HOME}/.kube -name '*.yaml') ; do echo -n ":${YAML}"; done)
kubectl config view --raw > tmp && mv tmp $HOME/.kube/config
chmod o-r $HOME/.kube/config
chmod g-r $HOME/.kube/config
```

Afterwards I source kubesess and set the config back.

**Comment by Ramilito** [comment]
And thanks for the prompt script, will try it out!

**Comment by MisterTimn** [comment]
> Do you mind if I copy this part to #26

Go ahead! fine for me. I'll chime in on the issue

**Comment by Ramilito** [comment]
@MisterTimn 
Played around with your script a bit and thought that I'd share it back!
Got rid of kube-ps1 just to simplify my zshrc file tbh and because it was pretty simple to do what it does.
 
<img width="552" alt="image" src="https://user-images.githubusercontent.com/8473233/189050006-41201e56-5de2-4683-9275-7d0d241d4b05.png">
