### ISSUE TITLE
Support multiple configs

### ISSUE THREAD

**Issue by Ramilito** [Ramilito/kubesess#26]
**Is your feature request related to a problem? Please describe.**

Need to support multiple config files

**Describe the solution you'd like**

If I have multiple config files, I would expect them to be merged into one

**Describe alternatives you've considered**

Manually merging them

**Comment by Ramilito** [comment]
<img width="459" alt="image" src="https://user-images.githubusercontent.com/8473233/188825045-dad1d6ef-b43d-4dbc-8be3-e4c9d3b4c84e.png">

This is one way of doing it, do we have other ideas?

**Comment by Ramilito** [comment]
Solved by merging all configs listed in the KUBECONFIG env.

**Comment by kcirrr** [comment]
Some alternatives allow configuring a path to read kubeconfigs from.
That way you have all your kubeconfigs in tact without merging them.

That might also be an option/idea.

**Comment by Ramilito** [comment]
@kcirrr The solution I implemented actually doesn't modify the files, the merge is made on runtime!

It's the same way kubectl recommends multiple config files by listing them in the path of kubeconfig environment.

But what I think you want is to point to a folder with a bunch of config files?

**Comment by Ramilito** [comment]
@kcirrr I think your solution is better, if we have loads of configs this might be a pain. 
We could have both also, they would run the same loop anyways, just on different paths.
I'll create a different issue about improving this feature with a path to a folder! Thanks for the great input 🙏
