### ISSUE TITLE
arm release

### ISSUE THREAD

**Issue by b4nst** [Ramilito/kubesess#4]
**Is your feature request related to a problem? Please describe.**

No release is available for arm target.

**Describe the solution you'd like**

Having a arm release would be nice.

**Describe alternatives you've considered**

`cargo install --git https://github.com/Ramilito/kubesess.git`

**Additional context**

**Comment by Ramilito** [comment]
That's a fair request, looked into the GitHub action I'm using and they don't support arm yet [support more targets](https://github.com/rust-build/rust-build.action/issues/4)

I will have to use something else. 
Really liked that one since it attaches binaries to the release automagically.

**Comment by Ramilito** [comment]
Just a note on your alternative solution.
The script kubesess.sh would need to be handled manually. 
Take a look at the command “deploy_local” in the Makefile for what steps are needed

**Comment by b4nst** [comment]
Yup, I'm using fish shell so I rebuilt the function and added completion manually. Can push them somewhere here if you're interested.

**Comment by Ramilito** [comment]
I’d love that! 
I do change that script sometimes, might be easier to maintain yours if it’s here as well.
Added a change default namespace feature recently for example.

**Comment by joberget** [comment]
@Ramilito an ARM release for M1 Macs will probably covered when kubesess will be available via brew? :)

**Comment by Ramilito** [comment]
touche @joberget, I will make it top-prio then! Hopefully this weekend 🤞

**Comment by Ramilito** [comment]
@b4nst I've included an arm target in the release now, not sure if it was precisely the one you wanted, if not please pick it out from this [list](https://github.com/cross-rs/cross#supported-targets)

@joberget Hit a road bump, need more stars on the repo to upload to homebrew apparently, created an [issue](https://github.com/Ramilito/kubesess/issues/7) about it

**Comment by Ramilito** [comment]
Closing this since the arm and fish scripts are merged (really nice code there @b4nst!) and add to brew has it's own issue

**Comment by joberget** [comment]
> Closing this since the arm and fish scripts are merged (really nice code there @b4nst!) and add to brew has it's own issue

@Ramilito great, thanks!
