### ISSUE TITLE
Better error handling

### ISSUE THREAD

**Issue by Ramilito** [Ramilito/kubesess#43]
**Is your feature request related to a problem? Please describe.**

We need to improve error handling, today all output is added to the env variable while all errors are swallowed and suppressed.
 
**Describe the solution you'd like**

As per @morozov suggestion in #42, we need to make the shell wrapper diffirentiate between stderr and stdout

**Describe alternatives you've considered**

Displaying the error inside the app and not using the stderr

**Comment by Ramilito** [comment]
@morozov Just tested this out within the app and it seems to work already for bash automatically, so I removed the error-suppressing handler and included it in #38

**Comment by morozov** [comment]
Error handling in Fish works fine. However, `kubesess` panicing in the case when an item was not selected in the interactive mode doesn't seem appropriate as of ffeb2d020ac16976cbe2478e8141c746b4c41743: https://github.com/Ramilito/kubesess/blob/b3e671b5cb5b778bee28813ba9873e07d1865e05/src/commands.rs#L79-L82

Now it looks like the following from the end-user perspective:
```shell
kubesess namespace
# Press ESC
thread 'main' panicked at 'No item selected', src/commands.rs:81:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
It should be fine to quietly exit with a non-zero code here. The wrappers will handle the exit code and not update the config. Printing the old config should be no longer necessary either (at least for how the Fish functions are now implemented).

**Comment by morozov** [comment]
@Ramilito please also see https://github.com/Ramilito/kubesess/pull/45. You may want to include it into the release.

**Comment by Ramilito** [comment]
@morozov I added a hot-fix for the not selected scenario, tried to avoid printing out the reset it but it messed up the environment variable for some reason, using this code at least works:
```zsh
    if selected_items.is_empty() {
        println!("{}", ORIGINALKUBECONFIG.to_string());
        process::exit(1);
    }
```

I thought bash wouldn't care about the non-zero exit, but it still did in this case, will modify the shell wrapper for that later and remove the extra pint!

**Comment by Ramilito** [comment]
Merged #45!
I'll use this build a day or two and create a release after that if no errors found!

**Comment by morozov** [comment]
> I thought bash wouldn't care about the non-zero exit, but it still did in this case, will modify the shell wrapper for that later and remove the extra print!

The current implementation indeed doesn't handle the exit codes. It needs to do something like this:
```shell
function kc() {
    local OUTPUT
    OUTPUT="$(echo 888)" || return $?
    export KUBECONFIG="$OUTPUT"
}
```

**Comment by Ramilito** [comment]
Fair enough created an issue for that, will look into it soon and also include a cleanup in that PR!
