### ISSUE TITLE
Create release binaries for mac

### ISSUE THREAD

**Issue by jankatins** [Ramilito/kubesess#50]
**Is your feature request related to a problem? Please describe.**

I want to install from a github release on a mac, the same as I do on linux, but the release binaries are only provided for linux.

**Describe the solution you'd like**

It seems it is possible to create rust binaries for mac in github actions, e.g. https://github.com/mitsuhiko/rye/blob/main/.github/workflows/release.yml

**Describe alternatives you've considered**

Use brew on mac or install from source, but that would mean a difference in my dotfiles between mac and linux.

**Comment by Ramilito** [comment]
Thank you for the example on how to implement this!

You should be able to find an OSX target now in the latest release!

**Comment by jankatins** [comment]
Thanks a lot, worked beautifully!
