### ISSUE TITLE
Fuzzy search visualization glitch

### ISSUE THREAD

**Issue by MisterTimn** [Ramilito/kubesess#62]
**Describe the bug**
When using fuzzy search to find context or namespace, selecting with arrows works fine, but when you start to search by typing the visualization glitches:

**To Reproduce**

1. enter `kubesess context` or `kubesess namespace`
2. start typing to search
3. Search works fine but the visualization glitches (letters arent cleared properly)

**Expected behavior**
See visual of clear screen with only the search hits visible, not floating characters (like fzf)

**Screenshots**
![image](https://github.com/user-attachments/assets/c772e1e1-3871-4d1e-82df-2c38e747c80a)

**Desktop (please complete the following information):**
 - OS: Fedora
 - Kubesess Version 2.0.1
 - Shell: zsh (also tested in bash shell)
 - Terminal: tested in both Gnome terminal and Alacritty

**Additional context**
I see the tool opted to use an own implementation of fuzzy searching instead of relying on fzf, perhaps it's this more recent change?

**Comment by Ramilito** [comment]
Should be fixed in #64! I updated the version for skim (the crate that does the fuzzy search) and I don't see any ui glitching anymore!
