### ISSUE TITLE
Release on brew

### ISSUE THREAD

**Issue by Ramilito** [Ramilito/kubesess#7]
**Is your feature request related to a problem? Please describe.**

I want to use homebrew to download

**Describe the solution you'd like**

want to be able to run the command brew install kubesess

**Describe alternatives you've considered**

Adding arm binary to releases helps a bit

**Additional context**

<img width="497" alt="image" src="https://user-images.githubusercontent.com/8473233/184479826-7687a854-c346-4df9-873c-1229ca154afb.png">

- [x] Upload formula
- [x] Make it a bottle
- [ ] Include alias and completion

**Comment by Ramilito** [comment]
When above 75 stars we can add this formula

```
class Kubesess < Formula
  desc "Manage multiple kubernetes cluster at the same time"
  homepage "https://rentarami.se/posts/2022-08-05-kube-context-2/"
  url "https://github.com/Ramilito/kubesess/archive/refs/tags/1.2.2.tar.gz"
  sha256 "237836053935a352bc61f362d1d2fd1892b0b1f49838b3c294ed1d81922d9328"
  license "MIT"

  depends_on "rust" => :build
  depends_on "kubernetes-cli" => :test

  def install
    system "cargo", "install", *std_cargo_args
  end

  test do
    shell_output("#{bin}/kubesess -v kubesess-test context")
    assert_predicate testpath/".kube/cache/kubesess-test", :exist?
  end
end
```

# Steps to take:
#  brew create --rust https://github.com/Ramilito/kubesess
#  use the formula above
#  brew install --build-from-source Kubesess
#  brew audit --strict --new-formula --online kubesess

**Comment by kostyay** [comment]
Reached 76 stars.. can create the brew package now :)

**Comment by Ramilito** [comment]
<img width="298" alt="image" src="https://user-images.githubusercontent.com/8473233/186111718-8cdd9ca3-348a-44b6-b2a3-e267d30ebbfb.png">

I think the repo was created 24 days ago, so 6 days left :(

**Comment by Ramilito** [comment]
PR up on brew, waiting for approval!
https://github.com/Homebrew/homebrew-core/pull/109171

**Comment by Ramilito** [comment]
It's now sort of in brew, It can be installed with:
```brew install --build-from-source kubesess```

This still requires you to manually download and source the two scripts needed, I'm working on including them and to make it possible to just type ```brew install kubesess```

*Note*
If anyone does use the --build-from-source option, remember that you need the scripts from the same version that's on brew!

**Comment by Ramilito** [comment]
Submittet a new PR:
https://github.com/Homebrew/homebrew-core/pull/109456

**Comment by Ramilito** [comment]
kubesess is now available on brew!
Updated readme to highlight one issue with the script for those that don't have completion setup.
